#!/bin/sh
file="`kde4-config --path data`"
BE_NETCFG="${file%%:*}be.shell/scripts/netcfg"
BE_WIFI_SELECT="${file%%:*}be.shell/scripts/wifi-select"
file="${file%%:*}be.shell/netcfg.xml"
CURRENT="`/usr/bin/netcfg current 2>/dev/null`"

STREAM="<menu>\n"
STREAM="${STREAM}<action label=\"Best\" exec=\"$BE_NETCFG __best\"/>\n"
for network in `netcfg -l`; do
    if [ "$network" != "$CURRENT" ]; then
        STREAM="${STREAM}<action label=\"$network\" exec=\"$BE_NETCFG $network\"/>\n"
    fi
done
STREAM="${STREAM}<separator/>\n"
STREAM="${STREAM}<action label=\"Scan Access Points\" exec=\"$BE_WIFI_SELECT\"/>\n"
if [ ! -z "$CURRENT" ]; then
    STREAM="${STREAM}<separator/>\n"
    STREAM="${STREAM}<action label=\"Disconnect\" exec=\"sudo netcfg -a\"/>\n"
fi
STREAM="${STREAM}<separator/>\n"
STREAM="${STREAM}<action label=\"Restart network\" exec=\"sudo /etc/rc.d/network restart\"/>\n"
STREAM="${STREAM}</menu>"
echo -e "${STREAM}" > "$file"
