#!/bin/sh

function join { local IFS="$1"; shift; echo "$*"; }

NONE="`echo $1 | tr -s '[:upper:]' '[:lower:]'`"
if [ "$NONE" != "none" ]; then
    IFS=':' read -a ELEMENTS <<< "$1"
    ELEMENTS=(${ELEMENTS[@]/\~\//$HOME/})
    COUNT=$((${#ELEMENTS[@]} - 1))
    for ((i=0; i < $COUNT; ++i)); do
        WALLPAPER="${WALLPAPER}`realpath ${ELEMENTS[$i]}`:"
    done
    WALLPAPER="${WALLPAPER}`realpath ${ELEMENTS[$COUNT]}`"
else
    WALLPAPER="none"
fi

if [ -z "$2" ]; then
    qdbus org.kde.be.shell /Desktop setWallpaper "$WALLPAPER"
else
    qdbus org.kde.be.shell /Desktop setWallpaper "$WALLPAPER" "$2"
fi
