#!/bin/sh
BASE="${1%%:*}"
TILE="${1##*:}"
if [ "$BASE" = "$TILE" ]; then
    WALLPAPER="`realpath $BASE`"
else
    WALLPAPER="`realpath $BASE`:`realpath $TILE`"
fi
if [ -z "$2" ]; then
    qdbus org.kde.be.shell /Desktop setWallpaper "$WALLPAPER"
else
    qdbus org.kde.be.shell /Desktop setWallpaper "$WALLPAPER" "$2"
fi
